# Generated by Django 3.2 on 2024-01-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="draft",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
