# Generated by Django 5.0.1 on 2024-02-15 15:01

from django.db import migrations, models

import Main.models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(
                max_length=12, validators=[Main.models.validate_number]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="gakka_category",
            field=models.CharField(
                choices=[
                    ("総合人間学科", "総合人間学科"),
                    ("人文学科", "人文学科"),
                    ("教育科学科", "教育科学科"),
                    ("経済経営学科", "経済経営学科"),
                    ("理学科", "理学科"),
                    ("医学科", "医学科"),
                    ("人間健康科学科", "人間健康科学科"),
                    ("薬科学科", "薬科学科"),
                    ("薬学科", "薬学科"),
                    ("地球工学科", "地球工学科"),
                    ("建築学科", "建築学科"),
                    ("物理工学科", "物理工学科"),
                    ("電気電子工学科", "電気電子工学科"),
                    ("情報学科", "情報学科"),
                    ("工業化学科", "工業化学科"),
                    ("資源生物科学科", "資源生物科学科"),
                    ("応用生命科学科", "応用生命科学科"),
                    ("地域環境工学科", "地域環境工学科"),
                    ("食料・環境経済学科", "食料・環境経済学科"),
                    ("森林科学科", "森林科学科"),
                    ("食品生物化学科", "食品生物科学科"),
                ],
                default="総合人間学科",
                max_length=20,
            ),
        ),
    ]
