# Generated by Django 5.0.1 on 2024-01-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0004_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="point",
            field=models.IntegerField(default=0),
        ),
    ]
