# Generated by Django 5.0.1 on 2024-02-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0005_customuser_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
