# Generated by Django 5.0.1 on 2024-02-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0006_like_is_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="is_available",
        ),
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
