# Generated by Django 5.0.1 on 2024-02-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_product_stripe_price_id_product_stripe_product_id'),
        ('Main', '0007_remove_like_is_available_product_is_available'),
    ]

    operations = [
    ]
