# Generated by Django 5.0.1 on 2024-02-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_customuser_email_alter_customuser_username'),
        ('Main', '0008_merge_20240205_1052'),
    ]

    operations = [
    ]
